import Footer from '@/Components/Frontend/Footer'
import Header from '@/Components/Frontend/Header'
import { Head } from '@inertiajs/react'
import React from 'react'
import { Container } from 'react-bootstrap'

const TermCondition = () => {
  return (
    <>
      <Header />
      <Head title="Terms & Conditions" />
      <section>
        <Container>
          <h3>Terms & Conditions</h3>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Possimus repellat doloribus assumenda adipisci molestias nostrum perferendis debitis error, accusamus obcaecati necessitatibus excepturi, architecto enim asperiores? Iure alias animi nostrum cum eius commodi esse in nemo tenetur magni quis dicta, aperiam, nobis possimus ex voluptatem! Fuga error ipsa quod, sequi officiis suscipit quisquam tempora sint, velit dolorum perspiciatis. Vitae dignissimos iste ipsam quidem suscipit nostrum, maxime repudiandae deleniti veniam numquam sunt doloremque natus libero eaque pariatur, officia eligendi error praesentium corrupti sed perferendis delectus nobis? Eos iusto architecto provident aliquid delectus odio voluptatem, voluptates, aspernatur at, corporis nulla molestiae porro tempora.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi molestias dolore atque dolorum quos aspernatur numquam nobis tempora libero, maxime cumque tempore itaque rerum, nostrum dolor corporis sunt dolores vel eaque. Inventore, sequi, blanditiis placeat quia nisi dicta provident animi officiis maxime doloribus quibusdam culpa autem perferendis in cupiditate tempore optio aliquam nostrum laborum delectus est ipsum? Deserunt maiores error officiis esse iste veniam fugit similique, qui voluptatum sed officia unde sapiente numquam temporibus enim velit ipsum hic ut, mollitia quas totam cupiditate? Vitae culpa accusamus, dolorem vero quos ab ex ea quia rem sit eveniet quasi ipsam aperiam omnis, veniam alias. Blanditiis error nam iste quidem nesciunt optio, enim debitis id rerum deserunt itaque labore accusamus dicta illum tenetur a ratione vero fugiat repudiandae dolorem commodi mollitia iusto! Similique enim odit rem iste nobis impedit tempore natus obcaecati quam at ipsum non, reprehenderit aut debitis nisi ad sequi quisquam adipisci maiores neque molestias velit laboriosam? Iure molestias eos tempora a, rem perspiciatis vitae veritatis voluptatem ratione. Quaerat consectetur, quisquam obcaecati illo provident dolorem, voluptate voluptates aliquam impedit cumque placeat amet iste, sit reprehenderit laudantium non nesciunt doloribus molestiae dignissimos id eius fuga? Dolore quibusdam animi, reiciendis distinctio possimus voluptatem ullam dignissimos aliquid, vitae, vel totam est? Nostrum iusto voluptatibus quidem veniam quo dolore error. Repudiandae quibusdam ullam laudantium vero provident dolorem, eaque exercitationem odio libero, praesentium delectus qui minima ut impedit? Excepturi fugit tempora possimus incidunt, tenetur libero quam hic molestias qui impedit. Nihil dignissimos ducimus enim ullam, magni architecto distinctio! Quis dolore porro incidunt corporis qui a quas, quibusdam harum libero pariatur, id nam obcaecati molestias natus dolorum sed labore laboriosam temporibus hic, exercitationem fuga perferendis aut fugit voluptate. Voluptatibus, doloremque impedit qui totam nam, obcaecati modi laboriosam exercitationem, delectus animi laborum quod dolores explicabo optio! Necessitatibus, hic.</p>
          <p>Lorem ipsum dolor sit amet consectetur, adipisicing elit. Possimus repellat doloribus assumenda adipisci molestias nostrum perferendis debitis error, accusamus obcaecati necessitatibus excepturi, architecto enim asperiores? Iure alias animi nostrum cum eius commodi esse in nemo tenetur magni quis dicta, aperiam, nobis possimus ex voluptatem! Fuga error ipsa quod, sequi officiis suscipit quisquam tempora sint, velit dolorum perspiciatis. Vitae dignissimos iste ipsam quidem suscipit nostrum, maxime repudiandae deleniti veniam numquam sunt doloremque natus libero eaque pariatur, officia eligendi error praesentium corrupti sed perferendis delectus nobis? Eos iusto architecto provident aliquid delectus odio voluptatem, voluptates, aspernatur at, corporis nulla molestiae porro tempora.</p>
          <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Modi molestias dolore atque dolorum quos aspernatur numquam nobis tempora libero, maxime cumque tempore itaque rerum, nostrum dolor corporis sunt dolores vel eaque. Inventore, sequi, blanditiis placeat quia nisi dicta provident animi officiis maxime doloribus quibusdam culpa autem perferendis in cupiditate tempore optio aliquam nostrum laborum delectus est ipsum? Deserunt maiores error officiis esse iste veniam fugit similique, qui voluptatum sed officia unde sapiente numquam temporibus enim velit ipsum hic ut, mollitia quas totam cupiditate? Vitae culpa accusamus, dolorem vero quos ab ex ea quia rem sit eveniet quasi ipsam aperiam omnis, veniam alias. Blanditiis error nam iste quidem nesciunt optio, enim debitis id rerum deserunt itaque labore accusamus dicta illum tenetur a ratione vero fugiat repudiandae dolorem commodi mollitia iusto! Similique enim odit rem iste nobis impedit tempore natus obcaecati quam at ipsum non, reprehenderit aut debitis nisi ad sequi quisquam adipisci maiores neque molestias velit laboriosam? Iure molestias eos tempora a, rem perspiciatis vitae veritatis voluptatem ratione. Quaerat consectetur, quisquam obcaecati illo provident dolorem, voluptate voluptates aliquam impedit cumque placeat amet iste, sit reprehenderit laudantium non nesciunt doloribus molestiae dignissimos id eius fuga? Dolore quibusdam animi, reiciendis distinctio possimus voluptatem ullam dignissimos aliquid, vitae, vel totam est? Nostrum iusto voluptatibus quidem veniam quo dolore error. Repudiandae quibusdam ullam laudantium vero provident dolorem, eaque exercitationem odio libero, praesentium delectus qui minima ut impedit? Excepturi fugit tempora possimus incidunt, tenetur libero quam hic molestias qui impedit. Nihil dignissimos ducimus enim ullam, magni architecto distinctio! Quis dolore porro incidunt corporis qui a quas, quibusdam harum libero pariatur, id nam obcaecati molestias natus dolorum sed labore laboriosam temporibus hic, exercitationem fuga perferendis aut fugit voluptate. Voluptatibus, doloremque impedit qui totam nam, obcaecati modi laboriosam exercitationem, delectus animi laborum quod dolores explicabo optio! Necessitatibus, hic.</p>
        </Container>
      </section>
      <Footer />
    </>
  )
}

export default TermCondition